"""empty message

Revision ID: 0aef5713f767
Revises: 9137fe0e864c
Create Date: 2024-07-23 15:33:11.285180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0aef5713f767"
down_revision: Union[str, None] = "9137fe0e864c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discount",
        "expires_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="EXTRACT(EPOCH FROM expires_at)::integer",
    )  # Update this line

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "discount",
        "expires_at",
        existing_type=sa.Integer(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="EXTRACT(EPOCH FROM expires_at)::integer",
    )
    # ### end Alembic commands ###
