"""empty message

Revision ID: 2bd3b7279f0a
Revises: 75a5b52c6a23
Create Date: 2024-07-04 15:23:13.983845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2bd3b7279f0a'
down_revision: Union[str, None] = '75a5b52c6a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price', sa.Column('unit_compare_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price', 'unit_compare_amount')
    # ### end Alembic commands ###
