"""empty message

Revision ID: 2d902df459ab
Revises: ea28df78f606
Create Date: 2024-07-10 17:21:22.441227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2d902df459ab'
down_revision: Union[str, None] = 'ea28df78f606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.create_foreign_key(None, '_discount_config_buy_x_get_y', 'variant', ['variant_get_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product', '_discount_config_off_product', ['discount_config_off_product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product', '_discount_config_buy_x_get_y', ['discount_config_buy_x_get_y_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, '_discount_config_buy_x_get_y', type_='foreignkey')
    op.create_table('review',
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('livemode', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shipping_rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', postgresql.ENUM('CUSTOMER_SERVICE', 'LOW_QUALITY', 'MISSING_FEATURES', 'TOO_COMPLEX', 'TOO_EXPENSIVE', 'UNUSED', 'OTHER', name='feedbackenum'), autoincrement=False, nullable=True),
    sa.Column('review', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('shop_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='review_customer_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='review_product_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='review_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='review_pkey'),
    sa.UniqueConstraint('customer_id', 'product_id', name='unique_product_customer_review')
    )
    # ### end Alembic commands ###
