"""empty message

Revision ID: 8f70fb93eada
Revises: b322301c90e7
Create Date: 2024-07-21 18:19:02.475185

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8f70fb93eada"
down_revision: Union[str, None] = "b322301c90e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "_subscription_pending_invoice_interval",
        "inteval_count",
        new_column_name="interval_count",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "_subscription_pending_invoice_interval",
        "interval_count",
        new_column="inteval_count",
    )
    # ### end Alembic commands ###
