"""empty message

Revision ID: 9ec5a0c08038
Revises: 993ce85e1781
Create Date: 2024-07-24 15:11:23.141846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ec5a0c08038"
down_revision: Union[str, None] = "993ce85e1781"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "variant",
        "next_refill",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="EXTRACT(EPOCH FROM next_refill)::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "variant",
        "next_refill",
        existing_type=sa.Integer(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
        postgresql_using="EXTRACT(EPOCH FROM next_refill)::integer",
    )
    # ### end Alembic commands ###
