"""empty message

Revision ID: a845781cd9a7
Revises: e1173cf4bafa
Create Date: 2024-07-04 21:22:48.513165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a845781cd9a7'
down_revision: Union[str, None] = 'e1173cf4bafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'cartitem', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartitem', type_='foreignkey')
    op.drop_column('cartitem', 'shop_id')
    # ### end Alembic commands ###
