"""empty message

Revision ID: b1e98509c6b0
Revises: 9ec5a0c08038
Create Date: 2024-07-24 15:26:13.070859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b1e98509c6b0"
down_revision: Union[str, None] = "9ec5a0c08038"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order",
        sa.Column(
            "channel",
            sa.Enum("TINYSHOP", name="orderchannelenum"),
            nullable=False,
            server_default="TINYSHOP",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "channel")
    # ### end Alembic commands ###
