"""empty message

Revision ID: ccd08d260923
Revises: 
Create Date: 2024-07-27 22:40:11.835839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccd08d260923'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('cart',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('REQUIRES_PAYMENT', 'ABANDONED', 'PAID', name='cartstatusenum'), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image_mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('otp', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discount',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('OFF_PRODUCT', 'OFF_ORDER', 'SHIPPING', 'BUY_X_GET_Y', name='discounttypeenum'), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('applies_max', sa.Integer(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('images', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('shippable', sa.Boolean(), nullable=False),
    sa.Column('preorder', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_config_off_product_id', sa.VARCHAR(), nullable=True),
    sa.Column('discount_config_buy_x_get_y_id', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['discount_config_buy_x_get_y_id'], ['_discount_config_buy_x_get_y.id'], use_alter=True),
    sa.ForeignKeyConstraint(['discount_config_off_product_id'], ['_discount_config_off_product.id'], use_alter=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'handle', name='unique_product_handle_shop')
    )
    op.create_table('secretkey',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_address',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_discount_config',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('discount_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discount_id')
    )
    op.create_table('_warehouse_address',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartdiscountlinks',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('discount_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.PrimaryKeyConstraint('discount_id', 'cart_id')
    )
    op.create_table('checkout',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ABANDONED', 'COMPLETE', 'EXPIRED', name='checkoutstatusenum'), nullable=False),
    sa.Column('payment_status', sa.Enum('PAID', 'UNPAID', name='checkoutpaymentstatus'), nullable=False),
    sa.Column('return_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('success_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount_total', sa.Integer(), nullable=False),
    sa.Column('amount_subtotal', sa.Integer(), nullable=False),
    sa.Column('amount_discount', sa.Integer(), nullable=False),
    sa.Column('amount_shipping', sa.Integer(), nullable=False),
    sa.Column('amount_tax', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_address_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['customer_address_id'], ['user_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collectionproductlink',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('collection_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('collection_id', 'product_id')
    )
    op.create_table('discountcustomerlink',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('discount_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.PrimaryKeyConstraint('discount_id', 'customer_id')
    )
    op.create_table('option',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('values', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'name', name='unique_option_name_product')
    )
    op.create_table('review',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_rating', sa.Integer(), nullable=False),
    sa.Column('shipping_rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Enum('CUSTOMER_SERVICE', 'LOW_QUALITY', 'MISSING_FEATURES', 'TOO_COMPLEX', 'TOO_EXPENSIVE', 'UNUSED', 'OTHER', name='feedbackenum'), nullable=True),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'product_id', name='unique_product_customer_review')
    )
    op.create_table('variant',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accept_zero_inventory_orders', sa.Boolean(), nullable=False),
    sa.Column('next_refill', sa.Integer(), nullable=True),
    sa.Column('unit_label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('product_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_discount_config_buy_x_get_y',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_min', sa.Integer(), nullable=True),
    sa.Column('amount_min', sa.Integer(), nullable=True),
    sa.Column('quantity_get', sa.Integer(), nullable=False),
    sa.Column('variant_get_id', sa.VARCHAR(), nullable=True),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['_discount_config.id'], ),
    sa.ForeignKeyConstraint(['variant_get_id'], ['variant.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id')
    )
    op.create_table('_discount_config_off_order',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_min', sa.Integer(), nullable=True),
    sa.Column('amount_min', sa.Integer(), nullable=True),
    sa.Column('amount_off', sa.Integer(), nullable=True),
    sa.Column('percentage_off', sa.Integer(), nullable=True),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['_discount_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id')
    )
    op.create_table('_discount_config_off_product',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_min', sa.Integer(), nullable=True),
    sa.Column('amount_off', sa.Integer(), nullable=True),
    sa.Column('percentage_off', sa.Integer(), nullable=True),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['_discount_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id')
    )
    op.create_table('_discount_config_shipping',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_min', sa.Integer(), nullable=True),
    sa.Column('amount_min', sa.Integer(), nullable=True),
    sa.Column('amount_off', sa.Integer(), nullable=True),
    sa.Column('percentage_off', sa.Integer(), nullable=True),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['_discount_config.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_id')
    )
    op.create_table('checkoutdiscountlinks',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('discount_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['discount_id'], ['discount.id'], ),
    sa.PrimaryKeyConstraint('discount_id', 'checkout_id')
    )
    op.create_table('inventory',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id', 'warehouse_id', name='unique_variant_warehouse')
    )
    op.create_table('invoice',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('amount_remaining', sa.Integer(), nullable=False),
    sa.Column('amount_shipping', sa.Integer(), nullable=False),
    sa.Column('amount_tax', sa.Integer(), nullable=False),
    sa.Column('amount_subtotal', sa.Integer(), nullable=False),
    sa.Column('amount_total', sa.Integer(), nullable=False),
    sa.Column('amount_discount', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('attempted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'PAID', 'UNCOLLECTIBLE', 'VOID', name='invoicestatusenum'), nullable=False),
    sa.Column('due_date', sa.Integer(), nullable=True),
    sa.Column('invoice_pdf', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('checkout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packagedimensions',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('variant_id')
    )
    op.create_table('price',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('type', sa.Enum('ONE_TIME', 'SUBSCRIPTION', name='pricetypeenum'), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.Column('unit_compare_amount', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_checkout_line_item',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('checkout_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_customer_unit_amount',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maximum', sa.Integer(), nullable=True),
    sa.Column('minimum', sa.Integer(), nullable=True),
    sa.Column('preset', sa.Integer(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_id')
    )
    op.create_table('_invoice_customer_address',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_recurring',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='recurringtypeenum'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_id')
    )
    op.create_table('cartitem',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cart_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PREORDER', 'DEFERRED', 'NORMAL', name='ordertypeenum'), nullable=False),
    sa.Column('status', sa.Enum('REQUIRES_INVENTORY', 'REQUIRES_SHIPPING', 'IN_SHIPPING', 'COMPLETED', 'RETURN_REQUESTED', name='orderstatusenum'), nullable=False),
    sa.Column('channel', sa.Enum('TINYSHOP', name='orderchannelenum'), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invoice_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('current_period_end', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INCOMPLETE', 'INCOMPLETE_EXPIRED', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'UNPAID', 'PAUSED', name='subscriptionstatusenum'), nullable=False),
    sa.Column('collection_method', sa.Enum('COLLECT_AUTOMATICALLY', 'SEND_INVOICE', name='collectionmethodenum'), nullable=False),
    sa.Column('billing_cycle_anchor', sa.Integer(), nullable=False),
    sa.Column('cancel_at', sa.Integer(), nullable=True),
    sa.Column('canceled_at', sa.Integer(), nullable=True),
    sa.Column('days_until_due', sa.Integer(), nullable=True),
    sa.Column('ended_at', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('next_pending_invoice', sa.Integer(), nullable=False),
    sa.Column('shop_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('customer_address_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['customer_address_id'], ['user_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_order_line_item',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_amount', sa.Integer(), nullable=False),
    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['price_id'], ['price.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_subscription_billing_cycle_anchor_config',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('second', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_subscription_cancellation_details',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('review', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('feedback', sa.Enum('CUSTOMER_SERVICE', 'LOW_QUALITY', 'MISSING_FEATURES', 'SWITCHED_SERVICE', 'TOO_COMPLEX', 'TOO_EXPENSIVE', 'UNUSED', 'OTHER', name='subscriptioncancellationdetailsfeedbackenum'), nullable=True),
    sa.Column('reason', sa.Enum('CANCELLATION_REQUESTED', 'PAYMENT_DISPUTED', 'PAYMENT_FAILED', name='subscriptioncancellationdetailsreasonenum'), nullable=True),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('_subscription_pending_invoice_interval',
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('livemode', sa.Boolean(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('interval', sa.Enum('DAY', 'WEEK', 'MONTH', 'YEAR', name='subscriptionpendinginvoiceintervalenum'), nullable=False),
    sa.Column('interval_count', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_subscription_pending_invoice_interval')
    op.drop_table('_subscription_cancellation_details')
    op.drop_table('_subscription_billing_cycle_anchor_config')
    op.drop_table('_order_line_item')
    op.drop_table('subscription')
    op.drop_table('order')
    op.drop_table('cartitem')
    op.drop_table('_recurring')
    op.drop_table('_invoice_customer_address')
    op.drop_table('_customer_unit_amount')
    op.drop_table('_checkout_line_item')
    op.drop_table('price')
    op.drop_table('packagedimensions')
    op.drop_table('invoice')
    op.drop_table('inventory')
    op.drop_table('checkoutdiscountlinks')
    op.drop_table('_discount_config_shipping')
    op.drop_table('_discount_config_off_product')
    op.drop_table('_discount_config_off_order')
    op.drop_table('_discount_config_buy_x_get_y')
    op.drop_table('variant')
    op.drop_table('review')
    op.drop_table('option')
    op.drop_table('discountcustomerlink')
    op.drop_table('collectionproductlink')
    op.drop_table('checkout')
    op.drop_table('cartdiscountlinks')
    op.drop_table('_warehouse_address')
    op.drop_table('_discount_config')
    op.drop_table('warehouse')
    op.drop_table('user_address')
    op.drop_table('secretkey')
    op.drop_table('product')
    op.drop_table('discount')
    op.drop_table('customer')
    op.drop_table('collection')
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('shop')
    # ### end Alembic commands ###
