"""empty message

Revision ID: e1173cf4bafa
Revises: 2bd3b7279f0a
Create Date: 2024-07-04 17:06:42.025406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1173cf4bafa'
down_revision: Union[str, None] = '2bd3b7279f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_variant_warehouse', 'inventory', ['variant_id', 'warehouse_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_variant_warehouse', 'inventory', type_='unique')
    # ### end Alembic commands ###
