"""empty message

Revision ID: fc7d611882c2
Revises: 9bd3172b680c
Create Date: 2024-07-19 21:14:44.690186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc7d611882c2'
down_revision: Union[str, None] = '9bd3172b680c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, '_discount_config_buy_x_get_y', 'variant', ['variant_get_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product', '_discount_config_buy_x_get_y', ['discount_config_buy_x_get_y_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product', '_discount_config_off_product', ['discount_config_off_product_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, '_discount_config_buy_x_get_y', type_='foreignkey')
    # ### end Alembic commands ###
