
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Transitions, { Animate } from "@/components/transitions";
import { Toaster } from "@/components/ui/sonner";
import ClientSideProvider from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <body className={inter.className}>
        <Transitions className="h-full flex flex-col">
          <Animate className="flex-1">
            {children}
          </Animate>
        </Transitions>
        <Toaster />
      </body>

    </html>
  );
}
