
import type { Metadata } from "next";
import { Inter, } from "next/font/google";
import "./globals.css";
import Transitions, { Animate } from "@/components/transitions";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="" data-theme="retro">
      <body className={inter.className}>
        {/* <Transitions>
          <Animate> */}
        {children}
        {/* </Animate>
        </Transitions> */}
        <Toaster />
      </body>

    </html>
  );
}
