from enum import Enum
from typing import TYPE_CHECKING
from sqlmodel import Field, Relationship


from lib.model import SqlBase
from lib.primary_key import get_primary_key
from price.enum import RecurringTypeEnum
from lib.enum import PaymentsProviderEnum


if TYPE_CHECKING:
    from shop.model import Shop
    from customer.model import Customer
    from user_address.model import UserAddress
    from price.model import Price
    from checkout.model import Checkout
    from invoice.model import Invoice


class SubscriptionStatusEnum(str, Enum):
    INCOMPLETE = "incomplete"
    INCOMPLETE_EXPIRED = "incomplete_expired"
    ACTIVE = "active"
    PAST_DUE = "past_due"
    CANCELED = "canceled"
    UNPAID = "unpaid"
    PAUSED = "paused"
    COMPLETED = "completed"


class CollectionMethodEnum(str, Enum):
    COLLECT_AUTOMATICALLY = "collect_automatically"
    SEND_INVOICE = "send_invoice"


class SubscriptionCancellationDetailsFeedbackEnum(str, Enum):
    CUSTOMER_SERVICE = "customer_service"
    LOW_QUALITY = "low_quality"
    MISSING_FEATURES = "missing_features"
    SWITCHED_SERVICE = "switched_service"
    TOO_COMPLEX = "too_complex"
    TOO_EXPENSIVE = "too_expensive"
    UNUSED = "unused"
    OTHER = "other"


class SubscriptionCancellationDetailsReasonEnum(str, Enum):
    CANCELLATION_REQUESTED = "cancellation_requested"
    PAYMENT_DISPUTED = "payment_disputed"
    PAYMENT_FAILED = "payment_failed"


class Subscription(SqlBase, table=True):
    id: str = Field(primary_key=True, default_factory=get_primary_key("sub"))
    cancel_at_period_end: bool = Field()
    current_period_end: int = Field()
    current_period_start: int = Field()
    status: SubscriptionStatusEnum = Field()
    collection_method: CollectionMethodEnum = Field()
    billing_cycle_anchor: int = Field()
    cancel_at: int = Field(nullable=True)
    canceled_at: int = Field(nullable=True)
    # Number of days a customer has to pay invoices generated by this subscription.
    # This value will be null for subscriptions where collection_method=charge_automatically.
    days_until_due: int = Field(nullable=True)
    ended_at: int = Field(nullable=True)
    start_date: int = Field()
    next_pending_invoice: int = Field()

    provider: PaymentsProviderEnum = Field()

    # Razorpay
    razorpay_plan_id: str = Field(nullable=True)
    razorpay_subscription_id: str = Field(nullable=True)

    # Pending Invoice Interval
    interval: RecurringTypeEnum = Field()
    interval_count: int = Field(default=1)

    # Billing Cycle Anchor Config
    day_of_month: int = (
        Field()
    )  # TODO if it's 31, generate next invoice on the last day of the month
    hour: int = Field(nullable=True)
    minute: int = Field(nullable=True)
    month: int = Field(nullable=True)
    second: int = Field(nullable=True)

    # Cancellation Details
    review: str = Field(nullable=True)
    feedback: SubscriptionCancellationDetailsFeedbackEnum = Field(nullable=True)
    reason: SubscriptionCancellationDetailsReasonEnum = Field(nullable=True)

    shop_id: str = Field(foreign_key="shop.id")
    shop: "Shop" = Relationship(back_populates="subscriptions")
    customer_id: str = Field(foreign_key="customer.id")
    customer: "Customer" = Relationship(back_populates="subscriptions")
    customer_address_id: str = Field(foreign_key="user_address.id")
    customer_address: "UserAddress" = Relationship(back_populates="subscriptions")
    checkout_id: str = Field(foreign_key="checkout.id")
    checkout: "Checkout" = Relationship(back_populates="subscriptions")
    line_items: list["SubscriptionLineItem"] = Relationship(
        back_populates="subscription",
        sa_relationship_kwargs={"cascade": "delete"},
    )
    invoices: list["Invoice"] = Relationship(back_populates="subscription")

    # TODO
    # latest_invoice - Maybe have a is_latest field in Invoice


class SubscriptionLineItem(SqlBase, table=True):
    id: str = Field(primary_key=True, default_factory=get_primary_key("subli"))
    quantity: int = Field(default=1)  # Quantity of the price

    price_id: str = Field(foreign_key="price.id")
    price: "Price" = Relationship(back_populates="subscription_line_items")

    subscription_id: str = Field(foreign_key="subscription.id")
    subscription: "Subscription" = Relationship(back_populates="line_items")

    # Notes
    # In Razorpay, these are added as add-ons when creating
    # subscription, so if you want to edit add-ons,
    # you need to cancel the subscription and create a new one.
