class ObjectType:
    CUSTOMER = "customer"
    CUSTOMER_ADDRESS = "customer_address"
    PRODUCT = "product"
    OPTION = "option"
    VARIANT = "variant"
    PRICE = "price"
    WAREHOUSE = "warehouse"
    INVENTORY = "inventory"
    CART = "cart"
    CART_ITEM = "cart_item"
    REVIEW = "review"
    DISCOUNT = "discount"
